name: we_cook
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/
  fonts:
    - family: Euclid
      fonts:
        - asset: lib/fonts/EuclidCircularA-Regular.ttf
          weight: 400
        - asset: lib/fonts/EuclidCircularA-SemiBold.ttf
          weight: 500
        - asset: lib/fonts/EuclidCircularA-Bold.ttf
          weight: 600

